# Dockerfile-nginx

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx_update_green.sh /etc/nginx/conf.d/nginx_update_green.sh
COPY nginx_update_blue.sh /etc/nginx/conf.d/nginx_update_blue.sh
RUN chmod 777 /etc/nginx/conf.d/nginx_update_green.sh
RUN chmod 777 /etc/nginx/conf.d/nginx_update_blue.sh
