# Generated by Django 4.1.10 on 2024-08-03 14:01
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('main_image_url', models.TextField(blank=True, null=True)),
                ('subscribed_count', models.BigIntegerField(db_index=True, default=0, help_text='현재 구독 수')),
                ('once_subscribed_count', models.BigIntegerField(db_index=True, default=0, help_text='지금까지 구독 수')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='map',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
