# Generated by Django 4.1.10 on 2024-08-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': '맵', 'verbose_name_plural': '맵'},
        ),
    ]
