# Generated by Django 4.1.10 on 2024-08-03 11:27
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '블랙리스트 섹션',
                'verbose_name_plural': '블랙리스트 섹션',
            },
        ),
        migrations.CreateModel(
            name='BlackListWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('black_list_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.blacklistsection')),
            ],
            options={
                'verbose_name': '블랙리스트 문구',
                'verbose_name_plural': '블랙리스트 문구',
            },
        ),
    ]
