# Generated by Django 4.1.10 on 2024-08-04 11:23
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_membermapsubscription_membernodeacquisition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrowAcquisitionQuestionMemberResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('PENDING', '답변중'), ('CORRECT', '정답'), ('WRONG', '오답')], max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArrowAcquisitionQuestionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('is_auto_mark', models.BooleanField(default=False)),
                ('is_always_correct', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrow_acquisition_rule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='network.arrowacquisitionrule')),
            ],
        ),
        migrations.CreateModel(
            name='ArrowAcquisitionQuestionMemberResponseReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(blank=True, null=True)),
                ('replied_status', models.CharField(choices=[('PENDING', '답변중'), ('CORRECT', '정답'), ('WRONG', '오답')], max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrow_acquisition_question_member_response', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='network.arrowacquisitionquestionmemberresponse')),
                ('replied_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='arrowacquisitionquestionmemberresponse',
            name='arrow_acquisition_question_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='network.arrowacquisitionquestionrule'),
        ),
        migrations.AddField(
            model_name='arrowacquisitionquestionmemberresponse',
            name='member_map_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.membermapsubscription'),
        ),
        migrations.AddField(
            model_name='arrowacquisitionquestionmemberresponse',
            name='question_member_response_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='network.arrowacquisitionquestionmemberresponsereply'),
        ),
        migrations.CreateModel(
            name='ArrowAcquisitionQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=256, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrow_acquisition_question_rule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='network.arrowacquisitionquestionrule')),
            ],
        ),
    ]
