# Generated by Django 4.1.10 on 2024-08-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_arrowacquisitionquestionmemberresponse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrow',
            options={'verbose_name': 'Arrow', 'verbose_name_plural': 'Arrow'},
        ),
        migrations.AlterModelOptions(
            name='arrowacquisitionquestionanswer',
            options={'verbose_name': 'Arrow 획득을 위한 조건 중 문제형: 정답', 'verbose_name_plural': 'Arrow 획득을 위한 조건 중 문제형: 정답'},
        ),
        migrations.AlterModelOptions(
            name='arrowacquisitionquestionmemberresponse',
            options={'verbose_name': 'Arrow 획득을 위한 조건 중 문제형: 사용자 답지', 'verbose_name_plural': 'Arrow 획득을 위한 조건 중 문제형: 사용자 답지'},
        ),
        migrations.AlterModelOptions(
            name='arrowacquisitionquestionmemberresponsereply',
            options={'verbose_name': 'Arrow 획득을 위한 조건 중 문제형: 채점자 답변', 'verbose_name_plural': 'Arrow 획득을 위한 조건 중 문제형: 채점자 답변'},
        ),
        migrations.AlterModelOptions(
            name='arrowacquisitionquestionrule',
            options={'verbose_name': 'Arrow 획득을 위한 조건 중 문제형: 문제', 'verbose_name_plural': 'Arrow 획득을 위한 조건 중 문제형: 문제'},
        ),
        migrations.AlterModelOptions(
            name='arrowacquisitionrule',
            options={'verbose_name': 'Arrow 획득을 위한 조건', 'verbose_name_plural': 'Arrow 획득을 위한 조건'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Node', 'verbose_name_plural': 'Node'},
        ),
        migrations.AlterModelOptions(
            name='nodeacquisitionrule',
            options={'verbose_name': 'Node 획득을 위한 조건', 'verbose_name_plural': 'Node 획득을 위한 조건'},
        ),
    ]
