# Generated by Django 4.1.10 on 2024-08-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_membermapsubscription_membernodeacquisition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberarrowacquisition',
            options={'verbose_name': '회원 Arrow 획득', 'verbose_name_plural': '회원 Arrow 획득'},
        ),
        migrations.AlterModelOptions(
            name='membernodeacquisition',
            options={'verbose_name': '회원 Node 획득', 'verbose_name_plural': '회원 Node 획득'},
        ),
    ]
