# Generated by Django 4.1.10 on 2024-08-03 11:27
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NORMAL_POINT', '포인트')], db_index=True, default='NORMAL_POINT', max_length=255)),
                ('point', models.BigIntegerField(db_index=True)),
                ('reason', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(db_index=True, null=True)),
                ('valid_until', models.DateTimeField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.guest')),
            ],
            options={
                'verbose_name': 'Guest 포인트',
                'verbose_name_plural': 'Guest 포인트',
            },
        ),
    ]
